
-- MySQL Script generated by MySQL Workbench
-- Sat Apr 16 14:25:23 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `ScoreBot` DEFAULT CHARACTER SET utf8 ;
USE `ScoreBot` ;

-- -----------------------------------------------------
-- Table `ScoreBot`.`Sports`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ScoreBot`.`Sports` (
  `SportsId` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  PRIMARY KEY (`SportsId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ScoreBot`.`Teams`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ScoreBot`.`Teams` (
  `TeamId` INT NOT NULL,
  `Name` VARCHAR(45) NULL,
  `Sports_SportsId` INT NOT NULL,
  PRIMARY KEY (`TeamId`, `Sports_SportsId`),
  INDEX `fk_Teams_Sports_idx` (`Sports_SportsId` ASC),
  CONSTRAINT `fk_Teams_Sports`
    FOREIGN KEY (`Sports_SportsId`)
    REFERENCES `ScoreBot`.`Sports` (`SportsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ScoreBot`.`Games`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ScoreBot`.`Games` (
  `GameId` INT NOT NULL,
  `AwayId` INT NULL,
  `Start` DATETIME NULL,
  `Finish` DATETIME NULL,
  `HomeScore` INT NULL,
  `AwayScore` INT NULL,
  `Status` VARCHAR(45) NULL,
  `homeId` INT NULL,
  PRIMARY KEY (`GameId`),
  INDEX `fk_Game_away_idx` (`AwayId` ASC),
  INDEX `fk_game_home_idx` (`homeId` ASC),
  CONSTRAINT `fk_Game_away`
    FOREIGN KEY (`AwayId`)
    REFERENCES `ScoreBot`.`Teams` (`TeamId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_game_home`
    FOREIGN KEY (`homeId`)
    REFERENCES `ScoreBot`.`Teams` (`TeamId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ScoreBot`.`Users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ScoreBot`.`Users` (
  `UserId` INT NOT NULL,
  `UserName` VARCHAR(45) NULL,
  `Platform` VARCHAR(45) NULL,
  `Phone` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `Joined` DATETIME NULL,
  `Userscol` VARCHAR(45) NULL,
  PRIMARY KEY (`UserId`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ScoreBot`.`Subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ScoreBot`.`Subscription` (
  `SubscriptionId` INT NOT NULL,
  `Users_UserId` INT NOT NULL,
  `Teams_TeamId` INT NOT NULL,
  `Teams_Sports_SportsId` INT NOT NULL,
  PRIMARY KEY (`SubscriptionId`, `Users_UserId`, `Teams_TeamId`, `Teams_Sports_SportsId`),
  INDEX `fk_Subscription_Users1_idx` (`Users_UserId` ASC),
  INDEX `fk_Subscription_Teams1_idx` (`Teams_TeamId` ASC, `Teams_Sports_SportsId` ASC),
  CONSTRAINT `fk_Subscription_Users1`
    FOREIGN KEY (`Users_UserId`)
    REFERENCES `ScoreBot`.`Users` (`UserId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Subscription_Teams1`
    FOREIGN KEY (`Teams_TeamId` , `Teams_Sports_SportsId`)
    REFERENCES `ScoreBot`.`Teams` (`TeamId` , `Sports_SportsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `ScoreBot`.`Events`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `ScoreBot`.`Events` (
  `EventId` INT NOT NULL,
  `Description` VARCHAR(45) NULL,
  `I` VARCHAR(45) NULL,
  `Games_GameId` INT NOT NULL,
  `Games_Teams_TeamId` INT NOT NULL,
  `Games_Teams_Sports_SportsId` INT NOT NULL,
  PRIMARY KEY (`EventId`, `Games_GameId`, `Games_Teams_TeamId`, `Games_Teams_Sports_SportsId`),
  INDEX `fk_Events_Games1_idx` (`Games_GameId` ASC, `Games_Teams_TeamId` ASC, `Games_Teams_Sports_SportsId` ASC),
  CONSTRAINT `fk_Events_Games1`
    FOREIGN KEY (`Games_GameId`)
    REFERENCES `ScoreBot`.`Games` (`GameId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
